#!/usr/bin/env bash

# This file exists solely to get `cimg-shared` to pass shellcheck.
# It's not actually used for real image builds.

repository=nothing
parent=nothing
variants=(node browsers)
namespace=nothing
versionTags=(9.9.9)
currentTag=2022.01